tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "neteasemusic"
cask "setapp"
cask "spotify"
cask "visual-studio-code"
cask "shadowsocksx-ng"
